### ISSUE TITLE
Rename visualize_inverse to plot_matrix_inverse

### ISSUE THREAD

**Issue by soumyaray** [soumyaray/compstatslib#13]
For consistency with other non-interactive visualization functions, follow the current convention of `plot_*()`.

**Comment by soumyaray** [comment]
@danielemelotti can you take a shot at this? Please use a new branch from develop and issue a PR to merge back into develop.

**Comment by danielemelotti** [comment]
I have created the PR and applied the requested name change in the script and documentation files as well.

**Comment by soumyaray** [comment]
thanks -- i've left a review comment (and request for change) regarding file names. Please let me know if you cannot find it.
