### ISSUE TITLE
IDEA: add features to interactive_t_test()

### ISSUE THREAD

**Issue by danielemelotti** [soumyaray/compstatslib#8]
It may be a good idea to display the power on the plot area of interactive_t_test() function.

**Comment by soumyaray** [comment]
@danielemelotti please update this with your latest ideas!  and feel free to make more issues with specific ideas we have green-lighted.

**Comment by danielemelotti** [comment]
IDEAS for updates:

- Write the rejection decision on screen,
         - (1) Write text AND/OR
         - (2) Change the color of the area under the alternative distribution depending on the test outcome
- Write the probability of Type I/II errors,
         - (1) Display 2x2 grid on plot area OR
         - (2) Write text only,
- Write the power level,
- Write confidence level,

**Comment by soumyaray** [comment]
@danielemelotti can we close this issue?

**Comment by danielemelotti** [comment]
@soumyaray I think so!

**Comment by soumyaray** [comment]
great!
